-- ============================================================================
--  Hackathon Judging System - PostgreSQL / Supabase schema
--  Safe to run more than once (everything is IF NOT EXISTS / OR REPLACE).
--
--  Run it either way:
--    a) Supabase Dashboard -> SQL Editor -> paste this whole file -> Run
--    b) npm run db:setup            (needs SUPABASE_DB_URL in .env)
--    c) psql "$SUPABASE_DB_URL" -f sql/001_schema.sql
--
--  SECURITY MODEL
--  Only the Node backend talks to these tables, using the direct Postgres
--  connection (or the service_role key), which bypasses RLS. Row Level
--  Security is enabled with NO policies and all grants to anon/authenticated
--  are revoked, so the public anon/publishable key can read NOTHING here.
--  That is what stops a judge from querying another judge's scores straight
--  from Supabase's REST API, bypassing the app.
-- ============================================================================

-- Timestamps are stored as ISO-8601 text (identical to the SQLite build),
-- so both drivers return the exact same value shapes to the application.
create or replace function public.judging_now() returns text
  language sql stable as
$$ select to_char((now() at time zone 'utc'), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

-- ---------------------------------------------------------------- faculties
create table if not exists public.faculties (
  id          integer generated by default as identity primary key,
  name        text not null,
  code        text,
  created_at  text not null default public.judging_now(),
  updated_at  text not null default public.judging_now()
);
create unique index if not exists ux_faculties_name on public.faculties (lower(name));
create unique index if not exists ux_faculties_code on public.faculties (lower(code)) where code is not null;

-- ------------------------------------------------------------------- panels
create table if not exists public.panels (
  id          integer generated by default as identity primary key,
  name        text not null,
  description text,
  created_at  text not null default public.judging_now(),
  updated_at  text not null default public.judging_now()
);
create unique index if not exists ux_panels_name on public.panels (lower(name));

-- -------------------------------------------------------------------- users
create table if not exists public.users (
  id                   integer generated by default as identity primary key,
  username             text not null,
  password_hash        text not null,          -- bcrypt; plain passwords are never stored
  name                 text not null,
  email                text,
  role                 text not null check (role in ('admin','judge')),
  panel_id             integer references public.panels(id) on delete set null,
  faculty_id           integer references public.faculties(id) on delete set null,
  is_active            integer not null default 1,
  must_change_password integer not null default 0,
  last_login_at        text,
  created_at           text not null default public.judging_now(),
  updated_at           text not null default public.judging_now()
);
create unique index if not exists ux_users_username on public.users (lower(username));

-- -------------------------------------------------------------------- teams
create table if not exists public.teams (
  id            integer generated by default as identity primary key,
  code          text,
  name          text not null,
  project_title text,
  members       text,
  description   text,                          -- shown to judges on the scoring form
  faculty_id    integer references public.faculties(id) on delete set null,
  panel_id      integer references public.panels(id) on delete set null,
  notes         text,
  created_at    text not null default public.judging_now(),
  updated_at    text not null default public.judging_now()
);
create unique index if not exists ux_teams_code on public.teams (lower(code)) where code is not null;
create index if not exists idx_teams_panel on public.teams (panel_id);
create index if not exists idx_teams_faculty on public.teams (faculty_id);

-- ----------------------------------------------------------------- criteria
create table if not exists public.criteria (
  id          integer generated by default as identity primary key,
  name        text not null,
  description text,
  max_marks   double precision not null check (max_marks > 0),
  sort_order  integer not null default 0,
  is_active   integer not null default 1,
  created_at  text not null default public.judging_now(),
  updated_at  text not null default public.judging_now()
);

-- -------------------------------------------------------------- assignments
create table if not exists public.assignments (
  id          integer generated by default as identity primary key,
  judge_id    integer not null references public.users(id) on delete cascade,
  team_id     integer not null references public.teams(id) on delete cascade,
  assigned_by integer references public.users(id) on delete set null,
  created_at  text not null default public.judging_now(),
  unique (judge_id, team_id)
);
create index if not exists idx_assign_judge on public.assignments (judge_id);
create index if not exists idx_assign_team on public.assignments (team_id);

-- ------------------------------------------------------------------- scores
-- One row per (judge, team). RAW marks only - normalization is never stored.
create table if not exists public.scores (
  id           integer generated by default as identity primary key,
  judge_id     integer not null references public.users(id) on delete restrict,
  team_id      integer not null references public.teams(id) on delete cascade,
  status       text not null default 'draft' check (status in ('draft','submitted')),
  comments     text,
  created_at   text not null default public.judging_now(),
  updated_at   text not null default public.judging_now(),
  submitted_at text,
  unique (judge_id, team_id)
);
create index if not exists idx_scores_team on public.scores (team_id);
create index if not exists idx_scores_judge on public.scores (judge_id);

create table if not exists public.score_items (
  id           integer generated by default as identity primary key,
  score_id     integer not null references public.scores(id) on delete cascade,
  criterion_id integer not null references public.criteria(id) on delete restrict,
  marks        double precision not null check (marks >= 0),
  unique (score_id, criterion_id)
);
create index if not exists idx_items_score on public.score_items (score_id);

-- Immutable journal: every saved version of every score. Never updated or
-- deleted by the application, so original judging data can never be lost.
create table if not exists public.score_history (
  id         integer generated by default as identity primary key,
  score_id   integer not null,
  judge_id   integer not null,
  team_id    integer not null,
  status     text not null,
  items_json text not null,
  total      double precision not null,
  comments   text,
  changed_by integer,
  changed_at text not null default public.judging_now()
);
create index if not exists idx_history_score on public.score_history (score_id);
create index if not exists idx_history_judge_team on public.score_history (judge_id, team_id);

-- ---------------------------------------------------------------- audit log
create table if not exists public.audit_log (
  id          integer generated by default as identity primary key,
  user_id     integer,
  username    text,
  role        text,
  action      text not null,
  entity_type text,
  entity_id   integer,
  details     text,
  ip          text,
  created_at  text not null default public.judging_now()
);
create index if not exists idx_audit_created on public.audit_log (created_at);
create index if not exists idx_audit_action on public.audit_log (action);

-- ----------------------------------------------------------------- settings
create table if not exists public.settings (
  key        text primary key,
  value      text not null,
  updated_at text not null default public.judging_now()
);

-- ----------------------------------------------------------------- sessions
-- Login sessions (express-session). expires_at is epoch milliseconds.
create table if not exists public.sessions (
  sid        text primary key,
  sess       text not null,
  expires_at bigint not null
);
create index if not exists idx_sessions_exp on public.sessions (expires_at);

-- ------------------------------------------------- raw totals, computed in DB
-- The raw total out of 100 is always derived from the criterion-wise marks;
-- it is never typed in or stored denormalised.
create or replace view public.v_score_totals as
  select s.id as score_id, s.judge_id, s.team_id, s.status, s.comments,
         s.created_at, s.updated_at, s.submitted_at,
         coalesce(sum(si.marks), 0) as total
  from public.scores s
  left join public.score_items si on si.score_id = s.id
  group by s.id;

-- ============================================================================
--  LOCK DOWN: no public/anon access to any judging data.
-- ============================================================================
alter table public.faculties     enable row level security;
alter table public.panels        enable row level security;
alter table public.users         enable row level security;
alter table public.teams         enable row level security;
alter table public.criteria      enable row level security;
alter table public.assignments   enable row level security;
alter table public.scores        enable row level security;
alter table public.score_items   enable row level security;
alter table public.score_history enable row level security;
alter table public.audit_log     enable row level security;
alter table public.settings      enable row level security;
alter table public.sessions      enable row level security;

-- Deliberately NO policies are created: with RLS on and no policy, anon and
-- authenticated can read/write nothing. Only the backend's direct Postgres
-- connection (and service_role) bypasses RLS.
--
-- Guarded so this file also runs on a plain PostgreSQL that has no Supabase
-- roles (local development, another host, the test suite).
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on all tables    in schema public from anon';
    execute 'revoke all on all sequences in schema public from anon';
    execute 'alter default privileges in schema public revoke all on tables    from anon';
    execute 'alter default privileges in schema public revoke all on sequences from anon';
    raise notice 'revoked public access from role anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on all tables    in schema public from authenticated';
    execute 'revoke all on all sequences in schema public from authenticated';
    execute 'alter default privileges in schema public revoke all on tables    from authenticated';
    execute 'alter default privileges in schema public revoke all on sequences from authenticated';
    raise notice 'revoked public access from role authenticated';
  end if;
end $$;

-- Sanity check: list what was created.
select table_name from information_schema.tables
where table_schema = 'public' order by table_name;
